/*
 * KV
 */

/* transition */
export const TOP_TRANSITION_KV_POSITION_START = 0
export const TOP_TRANSITION_KV_POSITION_END = 0
export const TOP_TRANSITION_KV_DISTANCE =
  TOP_TRANSITION_KV_POSITION_END - TOP_TRANSITION_KV_POSITION_START

/* main */
export const KV_TITLE_POSITION_START = 0
export const KV_TITLE_POSITION_END = KV_TITLE_POSITION_START + 400
export const KV_TITLE_DISTANCE = KV_TITLE_POSITION_END - KV_TITLE_POSITION_START

/*
 * Intro
 */

/* transition */
export const TOP_TRANSITION_INTRO_POSITION_START = 0
export const TOP_TRANSITION_INTRO_POSITION_END = 2000
export const TOP_TRANSITION_INTRO_DISTANCE =
  TOP_TRANSITION_INTRO_POSITION_END - TOP_TRANSITION_INTRO_POSITION_START

/* main */
export const INTRO_TITLE_POSITION_START =
  TOP_TRANSITION_INTRO_POSITION_START + 1500
export const INTRO_TITLE_POSITION_END = INTRO_TITLE_POSITION_START + 400
export const INTRO_TITLE_DISTANCE =
  INTRO_TITLE_POSITION_END - INTRO_TITLE_POSITION_START

export const INTRO_SLIDE_POSITION_START = INTRO_TITLE_POSITION_END + 100
export const INTRO_SLIDE_POSITION_END = INTRO_SLIDE_POSITION_START + 2000
export const INTRO_SLIDE_DISTANCE =
  INTRO_SLIDE_POSITION_END - INTRO_SLIDE_POSITION_START

export const INTRO_TEXT_POSITION_START = INTRO_SLIDE_POSITION_END
export const INTRO_TEXT_POSITION_END = INTRO_TEXT_POSITION_START + 3000
export const INTRO_TEXT_DISTANCE =
  INTRO_TEXT_POSITION_END - INTRO_TEXT_POSITION_START

export const INTRO_GO_NEXT_POSITION_START = INTRO_TEXT_POSITION_END
export const INTRO_GO_NEXT_POSITION_END = INTRO_GO_NEXT_POSITION_START + 500
export const INTRO_GO_NEXT_DISTANCE =
  INTRO_GO_NEXT_POSITION_END - INTRO_GO_NEXT_POSITION_START

export const SCROLL_TEXT_INTRO_POSITION = 0.5
export const SCROLL_TEXT_TRANSITION_POSITION = SCROLL_TEXT_INTRO_POSITION + 0.1

/*
 * 充電
 */

/* transition */
export const TOP_TRANSITION_CHARGING_POSITION_START =
  INTRO_GO_NEXT_POSITION_START
export const TOP_TRANSITION_CHARGING_POSITION_END =
  TOP_TRANSITION_CHARGING_POSITION_START + 2000
export const TOP_TRANSITION_CHARGING_DISTANCE =
  TOP_TRANSITION_CHARGING_POSITION_END - TOP_TRANSITION_CHARGING_POSITION_START

/* 車回転 */
export const CHARGING_CAR_POSITION_START =
  TOP_TRANSITION_CHARGING_POSITION_START
export const CHARGING_CAR_POSITION_END =
  TOP_TRANSITION_CHARGING_POSITION_END + 2000
export const CHARGING_CAR_DISTANCE =
  CHARGING_CAR_POSITION_END - CHARGING_CAR_POSITION_START

/* テキスト */
export const CHARGING_TEXT_POSITION_START = CHARGING_CAR_POSITION_END
export const CHARGING_TEXT_POSITION_END = CHARGING_TEXT_POSITION_START + 3000
export const CHARGING_TEXT_DISTANCE =
  CHARGING_TEXT_POSITION_END - CHARGING_TEXT_POSITION_START

/* メーター */
export const CHARGING_METER_START_RATE = 0.7
export const CHARGING_METER_POSITION_START =
  CHARGING_TEXT_POSITION_START +
  CHARGING_TEXT_DISTANCE * CHARGING_METER_START_RATE
export const CHARGING_METER_POSITION_END = CHARGING_TEXT_POSITION_END
export const CHARGING_METER_DISTANCE =
  CHARGING_METER_POSITION_END - CHARGING_METER_POSITION_START

/*
 * service
 */

/* transition */
export const TOP_TRANSITION_SERVICE_POSITION_START = CHARGING_METER_POSITION_END
export const TOP_TRANSITION_SERVICE_POSITION_END =
  TOP_TRANSITION_SERVICE_POSITION_START + 2000
export const TOP_TRANSITION_SERVICE_DISTANCE =
  TOP_TRANSITION_SERVICE_POSITION_END - TOP_TRANSITION_SERVICE_POSITION_START

/* タイトル */
export const SERVICE_TITLE_POSITION_START =
  TOP_TRANSITION_SERVICE_POSITION_END - TOP_TRANSITION_SERVICE_DISTANCE * 0.2
export const SERVICE_TITLE_POSITION_END =
  TOP_TRANSITION_SERVICE_POSITION_END - TOP_TRANSITION_SERVICE_DISTANCE * 0.1
export const SERVICE_TITLE_DISTANCE =
  SERVICE_TITLE_POSITION_END - SERVICE_TITLE_POSITION_START

/* テキスト */
export const SERVICE_TEXT_POSITION_START = TOP_TRANSITION_SERVICE_POSITION_END
export const SERVICE_TEXT_POSITION_END = SERVICE_TEXT_POSITION_START + 3000
export const SERVICE_TEXT_DISTANCE =
  SERVICE_TEXT_POSITION_END - SERVICE_TEXT_POSITION_START

/*
 * ServiceOpposite
 */

/* transition */
export const TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_START =
  SERVICE_TEXT_POSITION_END
export const TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_END =
  TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_START + 2000
export const TOP_TRANSITION_SERVICE_OPPOSITE_DISTANCE =
  TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_END -
  TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_START

/*
 * About
 */

/* transition */
export const TOP_TRANSITION_ABOUT_POSITION_START =
  TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_END + 4000
export const TOP_TRANSITION_ABOUT_POSITION_END =
  TOP_TRANSITION_ABOUT_POSITION_START + 2000
export const TOP_TRANSITION_ABOUT_DISTANCE =
  TOP_TRANSITION_ABOUT_POSITION_END - TOP_TRANSITION_ABOUT_POSITION_START

/* ServiceOpposite 車 */
export const SERVICE_OPPOSITE_CAR_POSITION_START =
  TOP_TRANSITION_SERVICE_OPPOSITE_POSITION_END
export const SERVICE_OPPOSITE_CAR_POSITION_END =
  TOP_TRANSITION_ABOUT_POSITION_END
export const SERVICE_OPPOSITE_CAR_DISTANCE =
  SERVICE_OPPOSITE_CAR_POSITION_END - SERVICE_OPPOSITE_CAR_POSITION_START

/* タイトル */
export const ABOUT_TITLE_POSITION_START =
  TOP_TRANSITION_ABOUT_POSITION_END - TOP_TRANSITION_ABOUT_DISTANCE * 0.2
export const ABOUT_TITLE_POSITION_END =
  TOP_TRANSITION_ABOUT_POSITION_END - TOP_TRANSITION_ABOUT_DISTANCE * 0.1
export const ABOUT_TITLE_DISTANCE =
  ABOUT_TITLE_POSITION_END - ABOUT_TITLE_POSITION_START

/* テキスト */
export const ABOUT_TEXT_POSITION_START = TOP_TRANSITION_ABOUT_POSITION_END
export const ABOUT_TEXT_POSITION_END = ABOUT_TEXT_POSITION_START + 3000
export const ABOUT_TEXT_DISTANCE =
  ABOUT_TEXT_POSITION_END - ABOUT_TEXT_POSITION_START

/* 鳥 */
export const ABOUT_BIRD_POSITION_START = ABOUT_TEXT_POSITION_END
export const ABOUT_BIRD_POSITION_END = ABOUT_BIRD_POSITION_START + 1000
export const ABOUT_BIRD_DISTANCE =
  ABOUT_BIRD_POSITION_END - ABOUT_BIRD_POSITION_START

/*
 * AboutBirdsEye
 */

/* transition */
export const TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_START =
  ABOUT_BIRD_POSITION_END
export const TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_END =
  TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_START + 2000
export const TOP_TRANSITION_ABOUT_BIRDS_EYE_DISTANCE =
  TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_END -
  TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_START

/* 走る */
export const ABOUT_BIRDS_EYE_RUN_POSITION_START =
  TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_START
export const ABOUT_BIRDS_EYE_RUN_POSITION_END =
  TOP_TRANSITION_ABOUT_BIRDS_EYE_POSITION_END + 6000
export const ABOUT_BIRDS_EYE_RUN_DISTANCE =
  ABOUT_BIRDS_EYE_RUN_POSITION_END - ABOUT_BIRDS_EYE_RUN_POSITION_START

/*
 * AboutSky
 */

/* transition */
export const TOP_TRANSITION_ABOUT_SKY_POSITION_START =
  ABOUT_BIRDS_EYE_RUN_POSITION_END - ABOUT_BIRDS_EYE_RUN_DISTANCE * 0.2
export const TOP_TRANSITION_ABOUT_SKY_POSITION_END =
  ABOUT_BIRDS_EYE_RUN_POSITION_END
export const TOP_TRANSITION_ABOUT_SKY_DISTANCE =
  TOP_TRANSITION_ABOUT_SKY_POSITION_END -
  TOP_TRANSITION_ABOUT_SKY_POSITION_START

/* テキスト */
export const ABOUT_SKY_TEXT_POSITION_START =
  TOP_TRANSITION_ABOUT_SKY_POSITION_END
export const ABOUT_SKY_TEXT_POSITION_END = ABOUT_SKY_TEXT_POSITION_START + 3000
export const ABOUT_SKY_TEXT_DISTANCE =
  ABOUT_SKY_TEXT_POSITION_END - ABOUT_SKY_TEXT_POSITION_START

/*
 * News
 */

/* transition */
export const TOP_TRANSITION_NEWS_POSITION_START = ABOUT_SKY_TEXT_POSITION_END
export const TOP_TRANSITION_NEWS_POSITION_END =
  TOP_TRANSITION_NEWS_POSITION_START + 2000
export const TOP_TRANSITION_NEWS_DISTANCE =
  TOP_TRANSITION_NEWS_POSITION_END - TOP_TRANSITION_NEWS_POSITION_START

const NEWS_SCROLL_DISTANCE = 1000
const NEWS_FADE_DISTANCE = 500

/* 吹き出し */
export const NEWS_BALLOON_POSITION_START =
  TOP_TRANSITION_NEWS_POSITION_START + TOP_TRANSITION_NEWS_DISTANCE * 0.8
export const NEWS_BALLOON_POSITION_END =
  NEWS_BALLOON_POSITION_START + NEWS_FADE_DISTANCE
export const NEWS_BALLOON_DISTANCE =
  NEWS_BALLOON_POSITION_END - NEWS_BALLOON_POSITION_START

/* コンテンツ2 */
export const NEWS_CONTENT_2_POSITION_START =
  NEWS_BALLOON_POSITION_END + NEWS_SCROLL_DISTANCE
export const NEWS_CONTENT_2_POSITION_END =
  NEWS_CONTENT_2_POSITION_START + NEWS_FADE_DISTANCE
export const NEWS_CONTENT_2_DISTANCE =
  NEWS_CONTENT_2_POSITION_END - NEWS_CONTENT_2_POSITION_START

/* コンテンツ3 */
export const NEWS_CONTENT_3_POSITION_START =
  NEWS_CONTENT_2_POSITION_END + NEWS_SCROLL_DISTANCE
export const NEWS_CONTENT_3_POSITION_END =
  NEWS_CONTENT_3_POSITION_START + NEWS_FADE_DISTANCE
export const NEWS_CONTENT_3_DISTANCE =
  NEWS_CONTENT_3_POSITION_END - NEWS_CONTENT_3_POSITION_START

/*
 * Footer
 */

/* transition */
export const TOP_TRANSITION_FOOTER_POSITION_START =
  NEWS_CONTENT_3_POSITION_END + NEWS_SCROLL_DISTANCE
export const TOP_TRANSITION_FOOTER_POSITION_END =
  TOP_TRANSITION_FOOTER_POSITION_START + NEWS_FADE_DISTANCE
export const TOP_TRANSITION_FOOTER_DISTANCE =
  TOP_TRANSITION_FOOTER_POSITION_END - TOP_TRANSITION_FOOTER_POSITION_START
